### ISSUE TITLE
Update value and set potential initial value

### ISSUE THREAD

**Issue by EmilTholin** [rehooks/local-storage#2]
This is super cool! You are really fast!

What are your thoughts on extending the API with something like `initValue` that would be used if the key has no value in localStorage? And maybe it could be useful to return the [`updateLocalState`](https://github.com/rehooks/local-storage/blob/dcca10383b52ee156b583337eb2968f11592382d/index.js#L9) function as well, so it can be updated in the component?

```javascript
import useLocalStorage from "@rehooks/local-storage";

function MyComponent() {
  let [name, setName] = useLocalStorage("name", { initValue: "Emil Tholin" });

  return (
    <div>
      <h1 onClick={() => setName("Eric Johnson")}>{name}</h1>
    </div>
  );
}
```

I understand perfectly well if you think this is outside the scope of the hook, but just thought I'd ask!

**Comment by iamsolankiamit** [comment]
Would you want to set the value in localStorage as well?

**Comment by EmilTholin** [comment]
I'm not entirely sure what would be best, to be honest. Some way of setting an initial value that persists to localStorage if there is none, as well as a bool like e.g. `clear` to force the localStorage to be cleared might be nice?

I haven't thought about it that deeply. What do you think?

**Comment by jamiebuilds** [comment]
The point of hooks is not to wrap every API, but to connect React to your environment or to your state or whatever. I think you should just use `localStorage.setItem`

**Comment by iamsolankiamit** [comment]
The idea by what I understood, was that data would flow from localStorage to the component. So to update the value you would use the `localStorage.setItem(key)` and the `useLocalStorage` hook would be used to subscribe to any change event there.

**Comment by EmilTholin** [comment]
Yeah, that makes sense. That's a much better idea. Thank you both.
