### ISSUE TITLE
Default value example in readme doesn't work

### ISSUE THREAD

**Issue by kokolem** [rehooks/local-storage#36]
Open your browser's developer tools to see the error on [codesandbox](https://codesandbox.io/s/cranky-archimedes-ckb8x?fontsize=14&hidenavigation=1&theme=dark
).
It seems that default value doesn't work for objects, which is exactly what is shown as an example in readme.

**Comment by jharrilim** [comment]
Looking into it!

**Comment by jharrilim** [comment]
https://github.com/rehooks/local-storage/pull/37

**Comment by kokolem** [comment]
The fix theoretically works, but the version (2.1.0) on NPM doesn't contain it. For some reason, it works on [codesandbox](https://codesandbox.io/s/rehooks-local-storage-default-value-ckb8x?fontsize=14&hidenavigation=1&theme=dark), but please try to run it locally (just click on export to zip and run `npm install`) and you'll see it's not working. If you look into `node_modules/@rehooks/local-storage`, in `src` the fix is implemented, but not in `lib` (it's still 1.7 in there).

**Comment by jharrilim** [comment]
@iamsolankiamit you may have to republish with running `npm run build` first

**Comment by kokolem** [comment]
I think this might be the problem:
As defined in `package.json`, `npm run build` will run `tsc`, not `tsc --build`.

**Comment by iamsolankiamit** [comment]
@kokolem `--build` flag is only for incremental builds, [build-mode-for-typescript](https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript).

@jharrilim I've republished it as `2.1.1`.

**Comment by kokolem** [comment]
I confirm that `2.1.1` contains the fix.
