### ISSUE TITLE
no-op error when unit testing custom hook

### ISSUE THREAD

**Issue by hanneswidrig** [rehooks/local-storage#41]
```
console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:131
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
        in TestHook
        in Suspense
        in Provider
        in wrapper
```

I am writing some unit tests for a complex React hook and have noticed an annoying error popping up in the terminal. My hook utilizes two `useLocalStorage` hooks. I don't experience any issues when running the application, it only seems to occur in my unit testing. _Really strange is the prerequisite that more than one `it()` unit test is required for this message to show up in the console.

My testing stack is using Jest included in `create-react-app` and `@testing-library/react-hooks`.

I'm not sure what information would be best to provide to help in determining the issue. It seems some kind of cleanup isn't occurring. I don't believe it's my fault given that I tried [this hook](https://github.com/dance2die/react-use-localstorage) which didn't display any errors in the same situation.

**Comment by mayteio** [comment]
@hanneswidrig the link to the test 404s. If it occurs when there are multiple it/test statements you might have to cleanup between tests. Are you mocking localStorage?

**Comment by hanneswidrig** [comment]
I apologize for not closing this bug. I'm not having this issue anymore. At the time I wasn't mocking localStorage though. If I run into this issue in the future, I will be sure to do that.
