### ISSUE TITLE
Unnecessary | null

### ISSUE THREAD

**Issue by ckknight** [rehooks/local-storage#50]
https://github.com/rehooks/local-storage/blob/025262932fa7b6bb6963b404405d79195204be03/src/use-localstorage.ts#L44

I believe `useLocalStorage` should have two separate exports:

```ts
export function useLocalStorage<TValue = string>(key: string): [TValue | null, (newValue: TValue) => void, () => void];
export function useLocalStorage<TValue = string>(key: string, initialValue: TValue): [TValue, (newValue: TValue) => void, () => void];
```

Notice the lack of `| null` on the second export, as it is guaranteed to be non-`null` by the specification of `initialValue`.

**Comment by jharrilim** [comment]
That is correct. Good catch!

**Comment by jharrilim** [comment]
#51
