### ISSUE TITLE
delete not detected across browser tabs?

### ISSUE THREAD

**Issue by mifi** [rehooks/local-storage#57]
First thanks for this extremely practical hook!

To reproduce the problem:

```js
const [val, setVal, deleteVal] = useLocalStorage('myval');

useEffect(() => console.log({ val }), [val]);
```

1. Run page in two tabs in Chrome.

2. When calling `deleteVal()` in one tab, the `useEffect` callback never gets fired in the other tab.

3. However, when calling `setVal(null)` in one tab, `useEffect` callback gets fired and logs `{val: undefined}`

So using `setVal(null)` instead of `deleteVal` is definitely a workaround, but it seems like `deleteVal` should also work.

**Comment by jharrilim** [comment]
I have done some debugging and I found the culprit:

https://github.com/rehooks/local-storage/blob/cdbe4e37d2b3f5fe887a0860369d8cf318b54d78/src/use-localstorage.ts#L58

Instead we should only check if it is undefined, as `null` is a valid value during deletion. That being said, our types are a bit off as well, and we will have to update the state value to be `TValue | null`.

**Comment by jharrilim** [comment]
cc: @iamsolankiamit

**Comment by iamsolankiamit** [comment]
Hey this is released here https://github.com/rehooks/local-storage/releases/tag/v2.4.1
