### ISSUE TITLE
Default value doesn't always work

### ISSUE THREAD

**Issue by mifi** [rehooks/local-storage#58]
Maybe I'm expecting too much, but when I do like this:
```js
const [user] = useLocalStorage('user', { name: 'Anakin Skywalker' });

return user.name;
```

...and I call this from somewhere in the code:
```js
deleteFromStorage('user');
```
...I get a crash because `user` is now `undefined` and the default value is no longer being presented.

Workaround is something like this:
```js
const [userUnsafe] = useLocalStorage('user');
const user = userUnsafe || { name: 'Anakin Skywalker' };
```

**Comment by jharrilim** [comment]
Closing, fixed in https://github.com/rehooks/local-storage/pull/59
