### ISSUE TITLE
Can't retrieve data after post call

### ISSUE THREAD

**Issue by martavis** [rehooks/local-storage#62]
I have a form with photo uploading and other text info. Like a normal React form, I'm saving the text to my local state, and using `useLocalStorage`. Once I upload an image, triggering a POST call, the localStorage state isn't being retrieved but it's fine otherwise. My code is like this:

```javascript
const [info, setInfo] = useLocalStorage<IInfo>('info', defaultInfo);

// uploading a photo here
const uploadPhoto = async (file: Blob):void => {
    const formData = new FormData();
    // append more formData

    try {
        const { data } = await axios.post('/upload', formData);
        console.log(info);
        console.log(localStorage.getItem('info'));
     } catch({ response }) {
         console.log(response);
         return;
     }
};
```

For some reason, the `info` state shows the default value, `defaultInfo`. However, the next line that directly gets the value from `localStorage` is correct, showing data that I previously saved. Also, I double-checked the React debugger and the state is correct, and I'm able to get the data just before the API call. Any idea why the state isn't retrieved after the POST call?

One thing I noticed is that there is no issue when I refresh the page. So it seems the state isn't updated at some level.

**Comment by jharrilim** [comment]
Hi there! I'm not entirely sure how to reproduce this but I have started here:

https://codesandbox.io/s/local-storage-62-fryys?file=/src/App.tsx

Is there somewhere in `uploadPhoto` where `setInfo` gets called?

**Comment by jharrilim** [comment]
Closing because inactive
