### ISSUE TITLE
Creates infinite loop when used in tandem with useEffect hook

### ISSUE THREAD

**Issue by theloni-monk** [rehooks/local-storage#64]
# I am getting an infinite loop when I try to do something like this:
The useEffect hook is triggering every update cycle even though the token isn't changing.
```javascript
  const [token] = useLocalStorage<token_format>('token'); // token is a json string with some internal token_format
  useEffect(()=> {
    try{
      if(token){
        //do something
      }
    }
    catch(e){
      console.log('Token not found: ', e);
    }
  }, [token])
```
This is the error React spits out:
> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

Apologies if this is formatted poorly this is my first issue submission.

**Comment by jharrilim** [comment]
Hello there, I'm afraid I cannot reproduce this:
![image](https://user-images.githubusercontent.com/19535809/86639202-8e3c1500-bfa6-11ea-83c7-5e23eac36d49.png)

Do you know if there is another component that is changing the `localStorage` value? That would trigger it.

**Comment by theloni-monk** [comment]
Apologies, the infinite loop in the useEffect hook was actually caused by an extremely nasty routing bug, not by the localStorage hook.

**Comment by jharrilim** [comment]
No problem at all. Good luck!
