### ISSUE TITLE
how to update the localStorage item?

### ISSUE THREAD

**Issue by HaNdTriX** [rehooks/local-storage#7]
This hook only allows us to read items from the `localStorage`.

How to actually set the item? Afaik the window `storage` event is only fired if you run `localStorage.setItem` from another tab. 🤔

https://github.com/rehooks/local-storage/blob/master/index.js#L16

**Comment by rosswaycaster** [comment]
@HaNdTriX I think the idea is to set the data with `localStorage.setItem(key)` and then use the `useLocalStorage` hook which will subscribe to any value change. [Check out this comment.](https://github.com/rehooks/local-storage/issues/2#issuecomment-433217092)

**Comment by HaNdTriX** [comment]
Afaik this doesn't work!

https://github.com/rehooks/local-storage/issues/6#issuecomment-439926885

**Comment by iamsolankiamit** [comment]
It can now be done using `writeStorage(key, value)` or `localStorage.setItem('key', 'value')`. check [version 1.1.0](https://github.com/rehooks/local-storage/releases/tag/v1.1.0)
